---
# https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#basic-authentication-git
# https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#guiding-credential-selection
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: tekton-pipelines
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: <base64 value of SSH Private Key>
  known_hosts: fDF8RWVPYU16Q3dZVUM2eDdIM3BsYTkvMFh3U0g4PXxHNm1tRFFhZEVmVUhRQTF6QWYwVHZEeEZiYXc9IHNzaC1yc2EgQUFBQUIzTnphQzF5YzJFQUFBQUJJd0FBQVFFQXEyQTdoUkdtZG5tOXRVRGJPOUlEU3dCSzZUYlFhK1BYWVBDUHk2cmJUclR0dzdQSGtjY0tycHAweVZocDVIZEVJY0tyNnBMbFZEQmZPTFg5UVVzeUNPVjB3emZqSUpObEdFWXNkbExKaXpIaGJuMm1VanZTQUhRcVpFVFlQODFlRnpMUU5uUEh0NEVWVlVoN1ZmREVTVTg0S2V6bUQ1UWxXcFhMbXZVMzEveU1mK1NlOHhoSFR2S1NDWklGSW1Xd29HNm1iVW9XZjluenBJb2FTakIrd2VxcVVVbXBhYWFzWFZhbDcySitVWDJCKzJSUFczUmNUMGVPelFncWxKTDNSS3JUSnZkc2pFM0pFQXZHcTNsR0hTWlh5MjhHM3NrdWEyU21WaS93NHlDRTZnYk9EcW5UV2xnNyt3QzYwNHlkR1hBOFZKaVM1YXA0M0pYaVVGRkFhUT09Cg==

---
# https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#kubernetess-docker-registrys-secret
# kubectl create secret docker-registry dockerhub-secret --from-file=.dockerconfigjson=/Users/vikas/.docker/config.json --type=kubernetes.io/dockerconfigjson --dry-run=client -o yaml
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: tekton-pipelines
  annotations:
    tekton.dev/docker-0: https://index.docker.io
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64 value of ~/.docker/config.json>
